### PR TITLE
Try to fix exiting.

### PR DESCRIPTION
**Pull request by V10lator**
Please note that this has not been tested as I don't manage to compile the cores, so merge at our own risk!

### CODE REVIEW

**Comment by Ploggy** [comment]
I gave this a try, I compiled and tested with the Genesis Plus GX Core:

Booting the Genesis Plus GX.RPX from the Homebrew Launcher - When I try to exit with Quit Retroarch the WiiU just stays on the WiiU Menu loading Screen. (music can still be heard)

Booting as a Channel - Game autoboots as its supposed to, pressing the Home Button does nothing, exiting with Quit Retroarch freezes Retroarch needing me to manually reset the WiiU.

If your having trouble Compiling Retroarch you can follow this guide, it uses Docker:
https://gbatemp.net/threads/retroarch-wiiu-wip.447670/page-619#post-9451333

**Comment by V10lator** [comment]
Thanks for trying. Yea, this PR might just fix one of many issues (this one fixes to call SYSRelaunchMenu() at all, the next one would be to handle home button press as a callback - @NicoAICP you can't use home like a regular button).

Also many thanks for the docker guide. I tried to not use docker but will have a look tomorrow.

**Comment by Ploggy** [comment]
No probs, happy to help :) especially if it leads to working Retroarch Channel/forwarders ;)
I had alot of problems trying to compile the usual way. Using that Docker guide was much easier and saved alot of headaches.

**Comment by NicoAICP** [comment]
Will try the commit, if it works imma merge

**Comment by NicoAICP** [comment]
Update: Managed to compile it and run it on wiiu.
Boots the game, on exit it is looping on the wiiu home menu.
As this is what it did before i will merge the pr, since it didnt break anything, sadly didnt fix (apperantly, atleast not seeing it rn) stuff

**Pull request merged**
